//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.11 at 08:16:57 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.approuter.com/schema/router/1000/security/03", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.approuter.schema.router._1000.security._03;
